update code for configure server

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -220,33 +220,47 @@ jobs:
           command: |
             pwd &&
             ls -la 
-            ct inventory 
+            cat inventory.txt 
             ansible-playbook -i inventory configure-server.yaml
             
       # Here's where you will add some code to rollback on failure      
 
-  #run-migrations:
-  #  docker:
-  #    # Docker image here that supports NodeJS
-  #      - image: circleci/node:13.8.0
-  #  steps:
-  #      - checkout 
-  #      - aws-cli/setup 
-  #    # Checkout code from git
-  #    - run:
-  #        name: Run migrations
-  #        command: |
-  #            cd backend
-  #            npm install 
-  #            npm run migrations > migrations_dump.txt 
-  #          # Your code here
-  #          exit 1
-  #    - run:
-  #        name: Send migration results to memstash
-  #        command: |
-  #          # Your code here
-  #          exit 1
-  #   # Here's where you will add some code to rollback on failure      
+  run-migrations:
+    docker:
+      # Docker image here that supports NodeJS
+        - image: circleci/node:13.8.0
+    steps:
+      - checkout 
+      - attach_workspace:
+          at: . 
+      - run:
+          name: Install AWS CLI dependencies
+          working_directory: /tmp
+          command: |
+            sudo apt-get update && sudo apt-get install -yy less
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip awscliv2.zip
+            sudo ./aws/install
+      # Checkout code from git
+      - run:
+          name: Run migrations
+          command: |
+              cd backend
+              npm install 
+              npm run migrations > migrations_dump.txt 
+            # Your code here
+            #exit 1
+      - run:
+          name: Send migration results to memstash
+          command: |
+            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+            then
+               # If you are using memstash.io, generate the token "7933fe63-4687-4fa1-8426-aa25aa1730ec" on the website
+               #curl -H "Content-Type: text/plain" -H "token: 7933fe63-4687-4fa1-8426-aa25aa1730ec" --request PUT --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
+               # If you are using kvdb.io, generate the bucket ID "9GE4jRtKznmVKRfvdBABBe" in your local terminal first
+               curl https://kvdb.io/G3uxHm9gAhAio27b61q5aC/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+            fi
+     # Here's where you will add some code to rollback on failure      
 
   #deploy-frontend:
   #  docker:
@@ -364,8 +378,8 @@ workflows:
     #          only: [test-feature-branch]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
-    #  - run-migrations:
-    #      requires: [configure-infrastructure]
+      - run-migrations:
+          requires: [configure-infrastructure]
     #  - deploy-frontend:
     #      requires: [run-migrations]
     #  - deploy-backend:
